on:
  
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - sonar-scan
  
name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
      # Triggering SonarQube analysis as results of it are required by Quality Gate check
    - name: Install SonarQube Scanner
      run: | 
        SONAR_SCANNER_VERSION="4.4.0" && \
        curl --insecure -L ${NEXUS2_SCM_TOOLS_URL}/sonar-scanner/${SONAR_SCANNER_VERSION}/sonar-scanner-${SONAR_SCANNER_VERSION}.zip -o /tmp/sonar-scanner.zip && \
        unzip -o -d /usr/bin/ /tmp/sonar-scanner.zip && mv /usr/bin/sonar-scanner-${SONAR_SCANNER_VERSION} /usr/bin/sonar-scanner && chmod -R 755 /usr/bin/sonar-scanner && rm -rf /tmp/sonar-scanner.zip
