# This is a basic workflow to help you get started with Actions

name: Sonar-Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Sonar Scanner
      - name: Install SonarQube Scanner
        run: | 
          SONAR_SCANNER_VERSION="4.4.0" && \
          curl --insecure -L ${NEXUS2_SCM_TOOLS_URL}/sonar-scanner/${SONAR_SCANNER_VERSION}/sonar-scanner-${SONAR_SCANNER_VERSION}.zip -o /tmp/sonar-scanner.zip && \
          unzip -o -d /usr/bin/ /tmp/sonar-scanner.zip && mv /usr/bin/sonar-scanner-${SONAR_SCANNER_VERSION} /usr/bin/sonar-scanner && chmod -R 755 /usr/bin/sonar-scanner && rm -rf /tmp/sonar-scanner.zip
          echo " Sonar Scanner Installed Successfully!!"
